name: t21_movie_searcher_rxdart_sqflite
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  sqflite: ^0.11.2+2
  rxdart: ^0.18.1
  path_provider: ^0.4.1


  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
