name: t3_http_requests
description: A new Flutter project.

dependencies:
  built_value: '>=5.5.5 < 7.0.0'
  built_collection: '>=2.0.0 <4.0.0'
  json_annotation: ^1.1.0
  http: ^0.11.3+17

  cupertino_icons: ^0.1.2

  flutter:
    sdk: flutter

dev_dependencies:

  build_runner: ^0.10.1+1
  built_value_generator: ^6.0.0  
  json_serializable: ^1.1.0
  flutter_stetho: 0.1.1

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true