name: just_flutteringgggg
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.15.7
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: FlamanteRoma
      fonts:
        - asset: assets/fonts/Flamante-Roma-Medium.ttf
        - asset: assets/fonts/Flamante-Roma-MediumItalic.ttf
          style: italic
    - family: bebas-neue
      fonts:
        - asset: assets/BebasNeue-Regular.ttf
    - family: mermaid
      fonts:
        - asset:  assets/Mermaid1001.ttf
