name: t38_41_weatherapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^1.1.0    
  geolocator: ^1.6.5  
  rx_command: ^3.0.0  
  rx_widgets: ^2.0.0  
  cupertino_icons: ^0.1.2
  charcode: ^1.1.2

dev_dependencies:
  build_runner: ^0.10.2
  json_serializable: ^1.2.1  
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
