name: built_value_tutorial
description: A new flutter application project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^6.1.4
  built_collection: ^4.0.0
  http: ^0.12.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  # build_runner: ^1.0.0 
  # built_value_generator: ^6.1.4
  


flutter:
  uses-material-design: true
  application:
    androidPackage: com.example.builtvaluetutorial
    iosBundleIdentifier: com.example.builtValueTutorial
