name: t42_videos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  chewie: ^0.7.0
  flutter_youtube: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

assets:
  - assets/videos/test.mp4
  - assets/videos/test2.mp4
  - assets/videos/intro.mp4
