name: t48_isolates
description: A new flutter application project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  application:
    androidPackage: com.example.t48isolates
    iosBundleIdentifier: com.example.t48Isolates
