name: redux_tutorial
description: A new flutter application project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.2
  shared_preferences: ^0.4.3
  flutter_redux_dev_tools: ^0.3.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  application:
    androidPackage: com.example.reduxtutorial
    iosBundleIdentifier: com.example.reduxTutorial
